### ISSUE TITLE
Where is the license?

### ISSUE THREAD

**Issue by narendasan** [HackIllinois/effective-goggles#1]
@redsn0w422  pls

**Comment by redsn0w422** [comment]
What license do you suggest?

**Comment by narendasan** [comment]
Something similar to BSD-3 clause (like NCSA/UIUC). With HackIllinois being a somewhat known brand that third clause is relevant

**Comment by narendasan** [comment]
unless you want copyleft

**Comment by redsn0w422** [comment]
open a PR

**Comment by redsn0w422** [comment]
added

**Comment by narendasan** [comment]
@redsn0w422  you have headers like this:
```
//
//  HackIllinois__QRTests.swift
//  HackIllinois: QRTests
//
//  Created by Yasha Mostofi on 2/12/17.
//  Copyright © 2017 Yasha Mostofi. All rights reserved.
//

```
which contradict the license. please change these to a header mentioning the license (look at groot if you want an example header)

**Comment by redsn0w422** [comment]
will do

**Comment by redsn0w422** [comment]
Resolved as of [v.2.5.3](https://github.com/HackIllinois/effective-goggles/releases/tag/v2.5.3)
